version: '3'
services:
  vault-server:
    image: vault:0.9.6
#    volumes:
#      - data/vault/:/vault/
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 8274d2a1-c80c-ff56-c6ed-1b99f7bcea78
    cap_add:
      - IPC_LOCK
    ports:
      - 127.0.0.1:8200:8200
  nc-vault-env:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./:/app
    restart: "no"
    environment:
      VAULT_ADDR: http://vault-server:8200
      VAULT_TOKEN: 8274d2a1-c80c-ff56-c6ed-1b99f7bcea78
#    command: ["npm", "run", "test-ci"]
    command: bash
    # hold container
    stdin_open: true
    depends_on:
      - vault-server
  vault-client:
    image: vault
    volumes:
      - ./:/app
    restart: "no"
    environment:
      VAULT_ADDR: http://vault-server:8200
      VAULT_TOKEN: 8274d2a1-c80c-ff56-c6ed-1b99f7bcea78
    command: sh
    # hold container
    stdin_open: true
    depends_on:
      - vault-server

